AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    Runtime: python3.9
    Architectures:
      - x86_64

Resources:
  ClaimManagementQueue:
    Type: AWS::SQS::Queue
  PatientCheckoutTopic:
    Type: AWS::SNS::Topic
  PatientCheckoutTopicDLQ:
    Type: AWS::SNS::Topic
  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  EventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref PatientCheckoutFunction
      MaximumEventAgeInSeconds: 60
      MaximumRetryAttempts: 0
      Qualifier: $LATEST
  PatientCheckoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patient-checkout/
      Handler: patientcheckout.lambda_handler
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref PatientCheckoutTopicDLQ
      Environment:
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref PatientCheckoutTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PatientCheckoutTopic.TopicName
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*
  BillManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patient-checkout/
      Handler: billmanagement.lambda_handler
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientCheckoutTopic
  ErrorHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patient-checkout/
      Handler: errorhandler.lambda_handler
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientCheckoutTopicDLQ
  ClaimManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patient-checkout/
      Handler: claimmanagement.lambda_handler
      Events:
        SNSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ClaimManagementQueue.Arn
            BatchSize: 2

